name: liquify
description: >
  A powerful and extensible Liquid template engine for Dart.
  Supports full Liquid syntax, custom tags and filters, and high-performance parsing and rendering.
version: 1.0.3
repository: https://github.com/kingwill101/liquify

topics:
  - liquid
  - templating
  - teamplate-engine
  - dart

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  petitparser: ^6.1.0
  html: ^0.15.5
  html_unescape: ^2.0.0
  intl: ^0.20.2
  timezone: ^0.10.0
  gato: ^0.0.5+1
  file: ^7.0.1
  args: ^2.7.0
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

funding:
  - https://www.buymeacoffee.com/kingwill101
