name: liquid_grammar
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.5.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  petitparser: ^6.0.2
  liquid_engine:
    path: ../liquid_dart

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
