name: liquify
description: >
  A powerful and extensible Liquid template engine for Dart.
  Supports full Liquid syntax, custom tags and filters, and high-performance parsing and rendering.
version: 0.8.1
repository: https://github.com/kingwill101/liquify

topics:
  - liquid
  - templating
  - teamplate-engine
  - dart

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  petitparser: ^6.0.2
  html: ^0.15.5
  html_unescape: ^2.0.0
  intl: ^0.19.0
  timezone: ^0.9.4
  gato: ^0.0.5+1
  file: ^7.0.1
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

funding:
  - https://www.buymeacoffee.com/kingwill101
