name: liquify
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  petitparser: ^6.0.2
  uuid: ^4.4.2
  macros:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
